[tool.poetry]
name = "goc"
version = "0.1.0"
description = ""
authors = ["Todd Perry <perry@nowcast.co.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
openai = "^0.27.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
